sudo: required

language: generic

services:
  - docker
  
env:
  - VOLUME_NAME="trik-checker-sandbox"  CONTAINER_NAME="trik-checker"
  
before_script:
  - echo "Downloading and setting up a docker image..."
  - sudo docker build -t checker https://github.com/anastasiia-kornilova/epicbox-images.git#xenial:/epicbox-trik -f Dockerfile.xenial
  - sudo docker volume create $VOLUME_NAME
  - volume_path=$(sudo docker volume inspect $VOLUME_NAME --format '{{.Mountpoint}}')
  
  - echo "Downloading checker rig..."
  - sudo svn checkout https://github.com/ibalashov24/semester_4_coursework/branches/travis-integration/TestScripts $volume_path/TestScripts
  - sudo cp -a "$volume_path/TestScripts/." "$volume_path"
  
  - echo "Preparing user solution file..."
  - sudo cp ./solution.js $volume_path/solution.js  
  
  - > 
    if  [ -d ./test_fields ] && ! [ `ls ./test_fields | wc -l` -eq 0 ] ; then 
      echo "Preparing user fields..."
      sudo cp -r ./test_fields/. $volume_path/custom_fields
    else
      echo "Fields not found in ./test_fields !!!"
      exit 1
    fi
  
script:
  - echo "Launching Docker container"
  - sudo docker images
  - >
    sudo docker run -i --name $CONTAINER_NAME -v $VOLUME_NAME:/trikStudio-checker/launch_scripts checker
    bash /trikStudio-checker/launch_scripts/start_testing.sh
    
after_success:
  - echo "TEST SUCCESS"
 
after_failure:
  - echo "TEST FAILURE"
  
